export const GET_ITEMS ='GET_ITEMS';
export const ADD_ITEM ='ADD_ITEM';
export const DELETE_ITEM ='DELETE_ITEM';
export const LOADING_ITEMS ='LOADING_ITEM';

export const GET_PRODUCTS ='GET_PRODUCT';
export const ADD_PRODUCT ='ADD_PRODUCT';
export const DELETE_PRODUCT ='DELETE_PRODUCT';
export const LOADING_PRODUCTS ='LOADING_PRODUCTS';

export const GET_ORDERS ='GET_ORDERS';
export const ADD_ORDER ='ADD_ORDER';
export const DELETE_ORDER  ='DELETE_ORDER ';
export const LOADING_ORDER  ='LOADING_ORDER';


//CUSTOMER ORDER ACTIONS
export const GET_USERORDERS = 'GET_USERORDERS';
export const ADD_USERORDER = 'ADD_USERORDER';
export const GET_USERORDER = 'GET_USERORDER';
export const DELETE_USERORDER = 'DELETE_USERORDER';
export const USERORDERS_LOADING = 'USERORDERS_LOADING';
export const SET_USERORDER_ID = 'SET_USERORDER_ID';
export const SET_USERORDER_NAME = 'SET_USERORDER_NAME';
export const GET_USERORDER_ID = 'GET_USERORDER_ID';
export const GET_USERORDER_NAME = 'GET_USERORDER_NAME';
export const SET_USERORDER_INFO = 'SET_USERORDER_INFO';
export const GET_USERORDER_INFO = 'GET_USERORDER_INFO';



//CUSTOMER ACTIONS
export const LOGIN ='LOGIN';
export const LOGOUT ='LOGOUT';
export const SIGNUP  ='SIGNUP';
export const GET_TOKEN  ='GET_TOKEN';

